export const CLOTHING_TYPES = [
  {label: 'Extras', value: 'extra'},
  {"parent": "extra", "label": "Hat", "value": "hat"},
  {"parent": "extra", "label": "Ring", "value": "ring"},
  {"parent": "extra", "label": "Scarf", "value": "scarf"},
  {"parent": "extra", "label": "Tie", "value": "tie"},
  {"parent": "extra", "label": "Belt", "value": "belt"},
  {"parent": "extra", "label": "Gloves", "value": "gloves"},
  {"parent": "extra", "label": "Socks", "value": "socks"},
  {"parent": "extra", "label": "Headband", "value": "headband"},
  {"parent": "extra", "label": "Bracelet", "value": "bracelet"},
  {"parent": "extra", "label": "Necklace", "value": "necklace"},
  {"parent": "extra", "label": "Earrings", "value": "earrings"},
  {"parent": "extra", "label": "Brooch", "value": "brooch"},
  {"parent": "extra", "label": "Pocket Square", "value": "pocket-square"},
  {"parent": "extra", "label": "Cufflinks", "value": "cufflinks"},
  {"parent": "extra", "label": "Watch", "value": "watch"},
  {"parent": "extra", "label": "Anklet", "value": "anklet"},
  {"parent": "extra", "label": "Sunglasses", "value": "sunglasses"},
  {"parent": "extra", "label": "Bowtie", "value": "bowtie"},
  {"parent": "extra", "label": "Suspender", "value": "suspender"},
  {"parent": "extra", "label": "Bandana", "value": "bandana"},
  {"parent": "extra", "label": "Shawl", "value": "shawl"},
  {"parent": "extra", "label": "Muffler", "value": "muffler"},
  {"parent": "extra", "label": "Tights", "value": "tights"},
  {"parent": "extra", "label": "Fascinator", "value": "fascinator"},
  {"parent": "extra", "label": "Pashmina", "value": "pashmina"},
  {"parent": "extra", "label": "Arm Warmers", "value": "arm-warmers"},

  {label: 'Top', value: 'top'},
  {"parent": "top", "label": "Sweater", "value": "sweater"},
  {"parent": "top", "label": "Shirt", "value": "shirt"},
  {"parent": "top", "label": "Blouse", "value": "blouse"},
  {"parent": "top", "label": "T-shirt", "value": "t-shirt"},
  {"parent": "top", "label": "Tank Top", "value": "tank-top"},
  {"parent": "top", "label": "Hoodie", "value": "hoodie"},
  {"parent": "top", "label": "Cardigan", "value": "cardigan"},
  {"parent": "top", "label": "Jacket", "value": "jacket"},
  {"parent": "top", "label": "Coat", "value": "coat"},
  {"parent": "top", "label": "Vest", "value": "vest"},
  {"parent": "top", "label": "Dress", "value": "dress"},
  {"parent": "top", "label": "Tunic", "value": "tunic"},
  {"parent": "top", "label": "Polo Shirt", "value": "polo-shirt"},
  {"parent": "top", "label": "Kimono", "value": "kimono"},
  {"parent": "top", "label": "Crop Top", "value": "crop-top"},
  {"parent": "top", "label": "Bodysuit", "value": "bodysuit"},
  {"parent": "top", "label": "Peplum Top", "value": "peplum-top"},
  {"parent": "top", "label": "Wrap Top", "value": "wrap-top"},
  {"parent": "top", "label": "Poncho", "value": "poncho"},
  {"parent": "top", "label": "Sweatshirt", "value": "sweatshirt"},
  {"parent": "top", "label": "Kaftan", "value": "kaftan"},
  {"parent": "top", "label": "Tube Top", "value": "tube-top"},
  {"parent": "top", "label": "Bustier", "value": "bustier"},
  {"parent": "top", "label": "Off-shoulder Top", "value": "off-shoulder-top"},
  {"parent": "top", "label": "Halter Top", "value": "halter-top"},
  {"parent": "top", "label": "Camisole", "value": "camisole"},
  {"parent": "top", "label": "Shrug", "value": "shrug"},

  {label: 'Bottom', value: 'bottom'},
  {"parent": "bottom", "label": "Jeans", "value": "jeans"},
  {"parent": "bottom", "label": "Pants", "value": "pants"},
  {"parent": "bottom", "label": "Skirt", "value": "skirt"},
  {"parent": "bottom", "label": "Shorts", "value": "shorts"},
  {"parent": "bottom", "label": "Leggings", "value": "leggings"},
  {"parent": "bottom", "label": "Trousers", "value": "trousers"},
  {"parent": "bottom", "label": "Jeggings", "value": "jeggings"},
  {"parent": "bottom", "label": "Culottes", "value": "culottes"},
  {"parent": "bottom", "label": "Dungarees", "value": "dungarees"},
  {"parent": "bottom", "label": "Capri Pants", "value": "capri-pants"},
  {"parent": "bottom", "label": "Palazzo Pants", "value": "palazzo-pants"},
  {"parent": "bottom", "label": "Cargo Pants", "value": "cargo-pants"},
  {"parent": "bottom", "label": "Harem Pants", "value": "harem-pants"},
  {"parent": "bottom", "label": "Pencil Skirt", "value": "pencil-skirt"},
  {"parent": "bottom", "label": "A-line Skirt", "value": "a-line-skirt"},
  {"parent": "bottom", "label": "Maxi Skirt", "value": "maxi-skirt"},
  {"parent": "bottom", "label": "Midi Skirt", "value": "midi-skirt"},
  {"parent": "bottom", "label": "Mini Skirt", "value": "mini-skirt"},
  {"parent": "bottom", "label": "Wrap Skirt", "value": "wrap-skirt"},
  {"parent": "bottom", "label": "Flare Pants", "value": "flare-pants"},
  {"parent": "bottom", "label": "Bootcut Jeans", "value": "bootcut-jeans"},
  {"parent": "bottom", "label": "Straight Pants", "value": "straight-pants"},
  {"parent": "bottom", "label": "Wide-leg Pants", "value": "wide-leg-pants"},
  {"parent": "bottom", "label": "High-waisted Pants", "value": "high-waisted-pants"},
  {"parent": "bottom", "label": "Cropped Pants", "value": "cropped-pants"},

  {label: 'Feet', value: 'feet'},
  {"parent": "feet", "label": "Sneakers", "value": "sneakers"},
  {"parent": "feet", "label": "Boots", "value": "boots"},
  {"parent": "feet", "label": "Flats", "value": "flats"},
  {"parent": "feet", "label": "Heels", "value": "heels"},
  {"parent": "feet", "label": "Oxfords", "value": "oxfords"},
  {"parent": "feet", "label": "Loafers", "value": "loafers"},
  {"parent": "feet", "label": "Sandals", "value": "sandals"},
  {"parent": "feet", "label": "Espadrilles", "value": "espadrilles"},
  {"parent": "feet", "label": "Mules", "value": "mules"},
  {"parent": "feet", "label": "Slippers", "value": "slippers"},
  {"parent": "feet", "label": "Flip-Flops", "value": "flip-flops"},
  {"parent": "feet", "label": "Wedges", "value": "wedges"},
  {"parent": "feet", "label": "Clogs", "value": "clogs"},
  {"parent": "feet", "label": "Platform Shoes", "value": "platform-shoes"},
  {"parent": "feet", "label": "Ankle Boots", "value": "ankle-boots"},
  {"parent": "feet", "label": "Brogues", "value": "brogues"},
  {"parent": "feet", "label": "Derby Shoes", "value": "derby-shoes"},
  {"parent": "feet", "label": "Chelsea Boots", "value": "chelsea-boots"},
  {"parent": "feet", "label": "Pumps", "value": "pumps"},
  {"parent": "feet", "label": "Athletic Shoes", "value": "athletic-shoes"},
  {"parent": "feet", "label": "Hiking Boots", "value": "hiking-boots"},
  {"parent": "feet", "label": "Dress Shoes", "value": "dress-shoes"},
  {"parent": "feet", "label": "Running Shoes", "value": "running-shoes"},
  {"parent": "feet", "label": "Boat Shoes", "value": "boat-shoes"},
  {"parent": "feet", "label": "Wingtip Shoes", "value": "wingtip-shoes"},
  {"parent": "feet", "label": "Mary Janes", "value": "mary-janes"},
  {"parent": "feet", "label": "Slingback Shoes", "value": "slingback-shoes"},
  {"parent": "feet", "label": "Peep-Toe Shoes", "value": "peep-toe-shoes"}]

export const CLOTHING_FABRICS = [
  {"label": "Cotton", "value": "cotton"},
  {"label": "Polyester", "value": "polyester"},
  {"label": "Silk", "value": "silk"},
  {"label": "Wool", "value": "wool"},
  {"label": "Linen", "value": "linen"},
  {"label": "Rayon", "value": "rayon"},
  {"label": "Nylon", "value": "nylon"},
  {"label": "Spandex", "value": "spandex"},
  {"label": "Acrylic", "value": "acrylic"},
  {"label": "Velvet", "value": "velvet"},
  {"label": "Satin", "value": "satin"},
  {"label": "Chiffon", "value": "chiffon"},
  {"label": "Denim", "value": "denim"},
  {"label": "Flannel", "value": "flannel"},
  {"label": "Tulle", "value": "tulle"},
  {"label": "Cashmere", "value": "cashmere"},
  {"label": "Leather", "value": "leather"},
  {"label": "Suede", "value": "suede"},
  {"label": "Corduroy", "value": "corduroy"},
  {"label": "Organza", "value": "organza"},
  {"label": "Tweed", "value": "tweed"},
  {"label": "Chambray", "value": "chambray"},
  {"label": "Taffeta", "value": "taffeta"},
  {"label": "Georgette", "value": "georgette"},
  {"label": "Jersey", "value": "jersey"},
  {"label": "Fleece", "value": "fleece"},
  {"label": "Brocade", "value": "brocade"},
  {"label": "Tencel", "value": "tencel"},
  {"label": "Hemp", "value": "hemp"},
  {"label": "Bamboo", "value": "bamboo"}
]
